from fpdf import FPDF
from datetime import datetime
import os
import re

def clean_text(text: str) -> str:
    """Remove or replace characters that can't be encoded in latin-1"""
    if not text:
        return ""
    text = text.replace('\u2014', '-')  # em dash
    text = text.replace('\u2013', '-')  # en dash
    text = text.replace('\u2018', "'")  # left single quote
    text = text.replace('\u2019', "'")  # right single quote
    text = text.replace('\u201c', '"')  # left double quote
    text = text.replace('\u201d', '"')  # right double quote
    text = text.replace('\u2022', '-')  # bullet
    text = text.replace('\u00e9', 'e')  # e accent
    text = text.encode('latin-1', errors='ignore').decode('latin-1')
    return text

class InterviewReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(107, 70, 193)
        self.cell(0, 10, 'Interview Prep AI - Session Report', align='C', new_x='LMARGIN', new_y='NEXT')
        self.set_draw_color(107, 70, 193)
        self.line(10, 25, 200, 25)
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated by Interview Prep AI - {datetime.now().strftime("%B %d, %Y")}', align='C')

def generate_report(session_data: dict) -> str:
    """Generate a PDF report from session data and return the file path"""
    pdf = InterviewReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    session = session_data['session']
    questions = session_data['questions']
    avg_score = session_data['average_score']

    # Session header
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, clean_text(f"{session['company_name']} - {session['role']}"), new_x='LMARGIN', new_y='NEXT')

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Date: {session['created_at'][:10]}", new_x='LMARGIN', new_y='NEXT')
    pdf.cell(0, 6, f"Total Questions: {session_data['total_questions']}", new_x='LMARGIN', new_y='NEXT')

    # Average score box
    pdf.ln(3)
    pdf.set_fill_color(245, 240, 255)
    pdf.set_draw_color(107, 70, 193)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.set_text_color(107, 70, 193)
    pdf.cell(0, 12, f'Average Score: {avg_score}/10', border=1, align='C', fill=True, new_x='LMARGIN', new_y='NEXT')
    pdf.ln(5)

    # Questions and answers
    for i, q in enumerate(questions):
        # Question
        pdf.set_font('Helvetica', 'B', 11)
        pdf.set_text_color(30, 30, 30)
        pdf.multi_cell(0, 7, clean_text(f"Q{i+1}: {q['question']}"))
        pdf.ln(2)

        # Score
        score = q.get('score', 0)
        if score >= 8:
            pdf.set_text_color(34, 139, 34)
        elif score >= 6:
            pdf.set_text_color(255, 140, 0)
        else:
            pdf.set_text_color(200, 50, 50)

        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(0, 6, f'Score: {score}/10', new_x='LMARGIN', new_y='NEXT')
        pdf.ln(1)

        # Answer
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(60, 60, 60)
        answer = clean_text(q.get('answer', 'No answer recorded'))
        pdf.multi_cell(0, 6, f"Your Answer: {answer}")
        pdf.ln(2)

        # Feedback
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(80, 80, 80)
        feedback = clean_text(q.get('feedback', 'No feedback recorded'))
        pdf.multi_cell(0, 5, feedback)
        pdf.ln(5)

        # Divider
        if i < len(questions) - 1:
            pdf.set_draw_color(200, 200, 200)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(5)

    # Save
    os.makedirs('data/reports', exist_ok=True)
    filename = f"data/reports/session_{session['id']}_{session['company_name'].replace(' ', '_')}.pdf"
    pdf.output(filename)
    print(f"Report generated: {filename}")
    return filename